name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "💡 feat [topic]: <title>"
labels: [
  "enhancement"
]
body:
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: Start of development
      placeholder: "year-month-day"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: "Tasks / To do"
      description: List here the steps to be taken
      value: |
        - [ ] Step_1
        - [ ] Step_2
      render: markdown
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks"
      description: What are the drawbacks/impacts of your feature request ?
      placeholder: Identify the drawbacks and impacts while being neutral on your feature request
    validations:
      required: false
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved ?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues or PRs"
      description: Common issues
      placeholder: "#Issues IDs"
    validations:
      required: false
