name: CI
env:
  node-version: 16.17.0

on:
  push:
  release:
    types: [published]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.NV }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NV }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run the lib tests
        run: yarn test:lib-ci
      - name: Build the lib
        run: yarn build:lib
      - name: Run the app tests
        run: yarn test:app-ci

  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.NV }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NV }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run the script
        run: yarn lint:ci

  build-lib-and-app:
    name: Build lib and app
    needs: [
      unit-tests,
      lint
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the lib
        run: yarn build:lib
      - name: Build the app
        run: yarn build:app

  release-please:
    name: Prepare next release
    runs-on: ubuntu-latest
    # Automate releases with Conventional Commit Messages as Pull Requests are merged into "main" branch
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get release please action
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
          package-name: ech-0160-DIMAG-Ingest
          changelog-types: '[
              {"type": "feat", "section": "Enhancements", "hidden": false },
              {"type": "fix", "section": "Bug Fixes", "hidden": false },
              {"type": "chore", "section": "Maintenance", "hidden": false },
              {"type": "refactor", "section": "Maintenance", "hidden": false },
              {"type": "docs", "section": "Documentation", "hidden": false }
            ]'
