name: Main CI/CD
env:
  nv: 16.17.0

on:
  push:
  release:
    types: [ published ]

jobs:
  # code linter
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nv }}
          cache: 'yarn'
      - name: Get cache path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Use cached node modules
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run the lint scripts
        run: |
          yarn lint-ci

  # unit tests
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nv }}
          cache: 'yarn'
      - name: Get cache path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Use cached node modules
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable && yarn postinstall
      - name: Run unit tests
        run: yarn test-ci

  # e2e tests
  e2e-tests:
    name: Run e2e tests (incl. build)
    runs-on: windows-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nv }}
      - name: Get cache path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Use cached node modules
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: D:\a\ech-0160-dimag-ingest\ech-0160-dimag-ingest\.yarn\cache # ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable && yarn postinstall
      - name: Build the app
        run: yarn build
      - name: Run e2e tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "electron ./testcafe-tests/main.spec.ts"

  # Automate releases with Conventional Commit Messages as Pull Requests are merged into "main" branch
  release-please:
    name: Prepare next release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.ref != 'refs/heads/deploy'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Run release please
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
          package-name: ech-0160-DIMAG-Ingest
          changelog-types: '[
              {"type": "feat", "section": "Enhancements", "hidden": false },
              {"type": "fix", "section": "Bug Fixes", "hidden": false },
              {"type": "chore", "section": "Maintenance", "hidden": false },
              {"type": "refactor", "section": "Maintenance", "hidden": false },
              {"type": "docs", "section": "Documentation", "hidden": false }
            ]'

  # deploy and publish; runs on release only
  publish:
    name: Publish
    # needs: [
    #   lint,
    #   unit-tests,
    #   e2e-tests
    # ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nv}}
          cache: 'yarn'
      - name: Get cache path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Use cached node modules
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable && yarn postinstall
      - name: Build the angular app
        run: yarn build
      - name: Publish the electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn publish

